name: grasp_generator
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - catkin_pkg
    - dotenv
    - empy
    - hydra-core
    - numpy
    - omegaconf
    - openai
    - opencv-python
    - requests
    - rospkg