name: transform_estimator
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - catkin_pkg
    - dotenv
    - empy
    - matplotlib
    - numpy
    - omegaconf
    - open3d
    - opencv-python
    - rospkg
    - scipy