# This path must be absolute (and valid inside the container).
hamer_data_dir: "/Handover_Pipeline/data/hamer/"
body_detector: "regnety" # 'regnety' or "vitdet"
rescale_factor: 2.0  # Padding around the detected boundary box for the hand
body_detector_confidence_threshold: 0.5 
hand_detector_confidence_threshold: 0.5

ros:
  node_name: "hand_reconstructor"  # Name of the ROS node

debug:
  # All output data will be saved to the output directory.
  # The directory can be set to a fixed path or dynamically set via the out_dir_topic.
  out_dir_mode: "topic"  # Options: "fixed", "topic"
  out_dir_topic: "/out_dir"  # Topic to set the output directory dynamically (if out_dir_mode is "topic")
  out_dir_fixed: "/Handover_Pipeline/outputs/" # Fixed output directory path (if out_dir_mode is "fixed")
  log_visualization: true  # Log a picture of the reconstructed hand