# This path must be absolute (and valid inside the container).
hamer_data_dir: "/Handover_Pipeline/data/hamer/"
body_detector: "regnety" # 'regnety' or "vitdet"
rescale_factor: 2.0  # Padding around the detected boundary box for the hand
body_detector_confidence_threshold: 0.5 
hand_detector_confidence_threshold: 0.5
focal_length: 909
img_size: 1280 # The maximum of the width and height of the input image.

ros:
  node_name: "hand_reconstructor"  # Name of the ROS node
  provided_services:
    reconstruct_hand: "reconstruct_hand"  # Service to reconstruct the hand from a given image
    reconstruct_hand_pose: "reconstruct_hand_pose"  # Service to reconstruct the hand pose from a given image
    estimate_camera: "estimate_camera"  # Service to estimate the camera parameters
    render_hand: "render_hand"  # Service to render the reconstructed hand
  published_topics:
    mesh_image: "/reconstructed_hand_mesh" # Publish an image with the reconstructed hand mesh

debug:
  # All output data will be saved to the output directory.
  # The directory can be set to a fixed path or dynamically set via the out_dir_topic.
  out_dir_mode: "topic"  # Options: "fixed", "topic"
  out_dir_topic: "/out_dir"  # Topic to set the output directory dynamically (if out_dir_mode is "topic")
  out_dir_fixed: "/Handover_Pipeline/outputs/" # Fixed output directory path (if out_dir_mode is "fixed")
  log_config: true  # Log the configuration used for the pipeline
  log_detections: false  # Log the detected hand and body probabilities (Attention: If true, data will be logged in every iteration of the main loop!)
  log_visualization:
    reconstruct_hand_pose: false  # Log a visualization of the reconstructed hand pose for the reconstruction service (Attention: If true, data will be logged in every iteration of the main loop!)
    reconstruct_hand: false  # Log a visualization of the reconstructed hand for the reconstruction service (This service will only be called up to once in the initialization step)
    estimate_camera: false  # Log a visualization of the estimated camera parameters for the camera estimation service (Attention: If true, data will be logged in every iteration of the main loop!)
  publish_visualization:
    reconstruct_hand_pose: true